/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;

pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub api_key: Option<String>,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }

    pub fn new_with_api_key<T: Into<String>>(api_key: T) -> Self {
        let mut result = Configuration::default();
        result.api_key = Some(api_key.into());
        result
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "https://api.themoviedb.org/3".to_owned(),
            user_agent: Some("OpenAPI-Generator/3/rust".to_owned()),
            client: reqwest::Client::new(),
            api_key: None,
        }
    }
}
