/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;

use super::{Error, configuration, urlencode};

pub struct MoviesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl MoviesApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> MoviesApiClient {
        MoviesApiClient {
            configuration: configuration,
        }
    }
}

pub trait MoviesApi {
    fn delete_movie_rating(&self, movie_id: i32, content_type: &str, guest_session_id: &str, session_id: &str) -> Result<crate::models::InlineResponse401, Error>;
    fn get_movie_account_states(&self, movie_id: &str, session_id: &str, guest_session_id: &str) -> Result<crate::models::AccountStates, Error>;
    fn get_movie_alternative_titles_list(&self, movie_id: i32, country: &str) -> Result<crate::models::AlternativeTitlesList, Error>;
    fn get_movie_changes_list(&self, movie_id: &str, start_date: String, end_date: String, page: i32) -> Result<crate::models::ChangeDetails, Error>;
    fn get_movie_credits(&self, movie_id: i32) -> Result<crate::models::Credits, Error>;
    fn get_movie_details(&self, movie_id: i32, language: &str, append_to_response: &str) -> Result<crate::models::MovieDetails, Error>;
    fn get_movie_images(&self, movie_id: i32, include_image_language: &str, language: &str) -> Result<crate::models::Images, Error>;
    fn get_movie_keywords_list(&self, movie_id: i32, api_key: &str) -> Result<crate::models::KeywordsList, Error>;
    fn get_movie_latest_details(&self, language: &str) -> Result<crate::models::MovieDetails, Error>;
    fn get_movie_lists_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::ListsPaginated, Error>;
    fn get_movie_now_playing_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error>;
    fn get_movie_popular_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error>;
    fn get_movie_recommendations_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::MoviePaginated, Error>;
    fn get_movie_release_dates(&self, movie_id: i32, api_key: &str) -> Result<crate::models::ReleaseDatesList, Error>;
    fn get_movie_reviews_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::ReviewsPaginated, Error>;
    fn get_movie_similar_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::MoviePaginated, Error>;
    fn get_movie_top_rated_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error>;
    fn get_movie_translations_list(&self, movie_id: i32, api_key: &str) -> Result<crate::models::Translations, Error>;
    fn get_movie_upcoming_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error>;
    fn get_movie_videos_list(&self, movie_id: &str, api_key: &str, language: &str) -> Result<crate::models::VideosList, Error>;
    fn post_movie_rating(&self, movie_id: i32, content_type: &str, guest_session_id: &str, session_id: &str, body: crate::models::ValueBody) -> Result<crate::models::InlineResponse401, Error>;
}

impl MoviesApi for MoviesApiClient {
    fn delete_movie_rating(&self, movie_id: i32, content_type: &str, guest_session_id: &str, session_id: &str) -> Result<crate::models::InlineResponse401, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/rating", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.delete(uri_str.as_str());

        req_builder = req_builder.query(&[("guest_session_id", &guest_session_id.to_string())]);
        req_builder = req_builder.query(&[("session_id", &session_id.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.header("Content-Type", content_type.to_string());

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_account_states(&self, movie_id: &str, session_id: &str, guest_session_id: &str) -> Result<crate::models::AccountStates, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/account_states", configuration.base_path, movie_id=urlencode(movie_id));
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("session_id", &session_id.to_string())]);
        req_builder = req_builder.query(&[("guest_session_id", &guest_session_id.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_alternative_titles_list(&self, movie_id: i32, country: &str) -> Result<crate::models::AlternativeTitlesList, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/alternative_titles", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("country", &country.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_changes_list(&self, movie_id: &str, start_date: String, end_date: String, page: i32) -> Result<crate::models::ChangeDetails, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/changes", configuration.base_path, movie_id=urlencode(movie_id));
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("start_date", &start_date.to_string())]);
        req_builder = req_builder.query(&[("end_date", &end_date.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_credits(&self, movie_id: i32) -> Result<crate::models::Credits, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/credits", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_details(&self, movie_id: i32, language: &str, append_to_response: &str) -> Result<crate::models::MovieDetails, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("append_to_response", &append_to_response.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_images(&self, movie_id: i32, include_image_language: &str, language: &str) -> Result<crate::models::Images, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/images", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("include_image_language", &include_image_language.to_string())]);
        req_builder = req_builder.query(&[("language", &language.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_keywords_list(&self, movie_id: i32, api_key: &str) -> Result<crate::models::KeywordsList, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/keywords", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_latest_details(&self, language: &str) -> Result<crate::models::MovieDetails, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/latest", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("language", &language.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_lists_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::ListsPaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/lists", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_now_playing_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/now_playing", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        req_builder = req_builder.query(&[("region", &region.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_popular_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/popular", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        req_builder = req_builder.query(&[("region", &region.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_recommendations_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::MoviePaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/recommendations", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_release_dates(&self, movie_id: i32, api_key: &str) -> Result<crate::models::ReleaseDatesList, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/release_dates", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_reviews_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::ReviewsPaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/reviews", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_similar_paginated(&self, movie_id: i32, api_key: &str, language: &str, page: i32) -> Result<crate::models::MoviePaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/similar", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_top_rated_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/top_rated", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        req_builder = req_builder.query(&[("region", &region.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_translations_list(&self, movie_id: i32, api_key: &str) -> Result<crate::models::Translations, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/translations", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_upcoming_paginated(&self, language: &str, page: i32, region: &str) -> Result<crate::models::MoviePaginated, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/upcoming", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("language", &language.to_string())]);
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        req_builder = req_builder.query(&[("region", &region.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_movie_videos_list(&self, movie_id: &str, api_key: &str, language: &str) -> Result<crate::models::VideosList, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/videos", configuration.base_path, movie_id=urlencode(movie_id));
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("api_key", &api_key.to_string())]);
        req_builder = req_builder.query(&[("language", &language.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn post_movie_rating(&self, movie_id: i32, content_type: &str, guest_session_id: &str, session_id: &str, body: crate::models::ValueBody) -> Result<crate::models::InlineResponse401, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/movie/{movie_id}/rating", configuration.base_path, movie_id=movie_id);
        let mut req_builder = client.post(uri_str.as_str());

        req_builder = req_builder.query(&[("guest_session_id", &guest_session_id.to_string())]);
        req_builder = req_builder.query(&[("session_id", &session_id.to_string())]);
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.query(&[("api_key", val)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.header("Content-Type", content_type.to_string());
        req_builder = req_builder.json(&body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
