/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct NetworksApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl NetworksApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> NetworksApiClient {
        NetworksApiClient {
            configuration,
        }
    }
}

pub trait NetworksApi {
    fn get_network_details(&self, network_id: i32) -> Result<crate::models::Network, Error>;
    fn get_network_alternative_names_list(&self, network_id: i32) -> Result<crate::models::AlternativeNamesList, Error>;
    fn get_network_images(&self, network_id: i32) -> Result<crate::models::Images, Error>;
}

impl NetworksApi for NetworksApiClient {
    fn get_network_details(&self, network_id: i32) -> Result<crate::models::Network, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let mut client = configuration.rate_limit_client();

        let uri_str = format!(
            "{}/network/{network_id}",
            configuration.base_path,
            network_id = network_id
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            req_builder = req_builder.query(&[("api_key", apikey)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_network_alternative_names_list(&self, network_id: i32) -> Result<crate::models::AlternativeNamesList, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let mut client = configuration.rate_limit_client();

        let uri_str = format!(
            "{}/network/{network_id}/alternative_names",
            configuration.base_path,
            network_id = network_id
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            req_builder = req_builder.query(&[("api_key", apikey)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_network_images(&self, network_id: i32) -> Result<crate::models::Images, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let mut client = configuration.rate_limit_client();

        let uri_str = format!(
            "{}/network/{network_id}/images",
            configuration.base_path,
            network_id = network_id
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref apikey) = configuration.api_key {
            req_builder = req_builder.query(&[("api_key", apikey)]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
