/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, Serialize, Deserialize)]
pub struct AccessTokenBody {
    #[serde(rename = "access_token")]
    pub access_token: String,
}

impl AccessTokenBody {
    pub fn new(access_token: String) -> AccessTokenBody {
        AccessTokenBody {
            access_token: access_token,
        }
    }
}


