/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AlternativeTitlesList {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "titles", skip_serializing_if = "Option::is_none")]
    pub titles: Option<Vec<crate::models::AlternativetitleslistTitles>>,
}

impl AlternativeTitlesList {
    pub fn new() -> AlternativeTitlesList {
        AlternativeTitlesList {
            id: None,
            titles: None,
        }
    }
}
