/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CertificationsCertifications {
    #[serde(rename = "BR", skip_serializing_if = "Option::is_none")]
    pub br: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "DE", skip_serializing_if = "Option::is_none")]
    pub de: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "AU", skip_serializing_if = "Option::is_none")]
    pub au: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "IN", skip_serializing_if = "Option::is_none")]
    pub india: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "GB", skip_serializing_if = "Option::is_none")]
    pub gb: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "FR", skip_serializing_if = "Option::is_none")]
    pub fr: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "NZ", skip_serializing_if = "Option::is_none")]
    pub nz: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "US", skip_serializing_if = "Option::is_none")]
    pub us: Option<Vec<crate::models::Certification>>,
    #[serde(rename = "CA", skip_serializing_if = "Option::is_none")]
    pub ca: Option<Vec<crate::models::Certification>>,
}

impl CertificationsCertifications {
    pub fn new() -> CertificationsCertifications {
        CertificationsCertifications {
            br: None,
            de: None,
            au: None,
            india: None,
            gb: None,
            fr: None,
            nz: None,
            us: None,
            ca: None,
        }
    }
}
