/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct ExternalIds {
    #[serde(rename = "id")]
    pub id: Option<i32>,
    #[serde(rename = "imdb_id")]
    pub imdb_id: Option<String>,
    #[serde(rename = "facebook_id")]
    pub facebook_id: Option<String>,
    #[serde(rename = "freebase_mid")]
    pub freebase_mid: Option<String>,
    #[serde(rename = "freebase_id")]
    pub freebase_id: Option<String>,
    #[serde(rename = "tvrage_id")]
    pub tvrage_id: Option<i32>,
    #[serde(rename = "twitter_id")]
    pub twitter_id: Option<String>,
    #[serde(rename = "instagram_id")]
    pub instagram_id: Option<String>,
}
