/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineObject8 {
    #[serde(rename = "media_type")]
    pub media_type: String,
    #[serde(rename = "media_id")]
    pub media_id: i32,
    #[serde(rename = "watchlist")]
    pub watchlist: bool,
}

impl InlineObject8 {
    pub fn new(media_type: String, media_id: i32, watchlist: bool) -> InlineObject8 {
        InlineObject8 {
            media_type: media_type,
            media_id: media_id,
            watchlist: watchlist,
        }
    }
}

/// 
#[derive(Debug, Serialize, Deserialize)]
pub enum MediaType {
    #[serde(rename = "movie")]
    Movie,
    #[serde(rename = "tv")]
    Tv,
}

