/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20075OriginalValue {
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<::models::InlineResponse20075OriginalValueProfile>,
}

impl InlineResponse20075OriginalValue {
    pub fn new() -> InlineResponse20075OriginalValue {
        InlineResponse20075OriginalValue {
            profile: None,
        }
    }
}


