/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20083Episodes {
    #[serde(rename = "air_date", skip_serializing_if = "Option::is_none")]
    pub air_date: Option<String>,
    #[serde(rename = "overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(rename = "episode_number", skip_serializing_if = "Option::is_none")]
    pub episode_number: Option<i32>,
    #[serde(rename = "vote_average", skip_serializing_if = "Option::is_none")]
    pub vote_average: Option<f32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "season_number", skip_serializing_if = "Option::is_none")]
    pub season_number: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "still_path", skip_serializing_if = "Option::is_none")]
    pub still_path: Option<Value>,
    #[serde(rename = "vote_count", skip_serializing_if = "Option::is_none")]
    pub vote_count: Option<i32>,
    #[serde(rename = "crew", skip_serializing_if = "Option::is_none")]
    pub crew: Option<Vec<::models::InlineResponse20083Crew>>,
    #[serde(rename = "guest_stars", skip_serializing_if = "Option::is_none")]
    pub guest_stars: Option<Vec<Value>>,
}

impl InlineResponse20083Episodes {
    pub fn new() -> InlineResponse20083Episodes {
        InlineResponse20083Episodes {
            air_date: None,
            overview: None,
            episode_number: None,
            vote_average: None,
            name: None,
            season_number: None,
            id: None,
            still_path: None,
            vote_count: None,
            crew: None,
            guest_stars: None,
        }
    }
}


