/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20053Certifications {
    #[serde(rename = "BR", skip_serializing_if = "Option::is_none")]
    pub br: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "DE", skip_serializing_if = "Option::is_none")]
    pub de: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "RU", skip_serializing_if = "Option::is_none")]
    pub ru: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "AU", skip_serializing_if = "Option::is_none")]
    pub au: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "TH", skip_serializing_if = "Option::is_none")]
    pub th: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "KR", skip_serializing_if = "Option::is_none")]
    pub kr: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "GB", skip_serializing_if = "Option::is_none")]
    pub gb: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "FR", skip_serializing_if = "Option::is_none")]
    pub fr: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "US", skip_serializing_if = "Option::is_none")]
    pub us: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "CA", skip_serializing_if = "Option::is_none")]
    pub ca: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
}

impl InlineResponse20053Certifications {
    pub fn new() -> InlineResponse20053Certifications {
        InlineResponse20053Certifications {
            br: None,
            de: None,
            ru: None,
            au: None,
            th: None,
            kr: None,
            gb: None,
            fr: None,
            us: None,
            ca: None,
        }
    }
}
