/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20059 {
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<::models::InlineResponse20059Images>,
    #[serde(rename = "change_keys", skip_serializing_if = "Option::is_none")]
    pub change_keys: Option<Vec<String>>,
}

impl InlineResponse20059 {
    pub fn new() -> InlineResponse20059 {
        InlineResponse20059 {
            images: None,
            change_keys: None,
        }
    }
}


