/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20036Translations {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<::models::InlineResponse20036Data>,
    #[serde(rename = "iso_3166_1", skip_serializing_if = "Option::is_none")]
    pub iso_3166_1: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "iso_639_1", skip_serializing_if = "Option::is_none")]
    pub iso_639_1: Option<String>,
    #[serde(rename = "english_name", skip_serializing_if = "Option::is_none")]
    pub english_name: Option<String>,
}

impl InlineResponse20036Translations {
    pub fn new() -> InlineResponse20036Translations {
        InlineResponse20036Translations {
            data: None,
            iso_3166_1: None,
            name: None,
            iso_639_1: None,
            english_name: None,
        }
    }
}


