/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20084 {
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "request_token", skip_serializing_if = "Option::is_none")]
    pub request_token: Option<String>,
}

impl InlineResponse20084 {
    pub fn new() -> InlineResponse20084 {
        InlineResponse20084 {
            expires_at: None,
            success: None,
            request_token: None,
        }
    }
}


