/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20066 {
    #[serde(rename = "cast", skip_serializing_if = "Option::is_none")]
    pub cast: Option<Vec<::models::InlineResponse20066Cast>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "crew", skip_serializing_if = "Option::is_none")]
    pub crew: Option<Vec<::models::InlineResponse20011Crew>>,
}

impl InlineResponse20066 {
    pub fn new() -> InlineResponse20066 {
        InlineResponse20066 {
            cast: None,
            id: None,
            crew: None,
        }
    }
}


