/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineObject11 {
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl InlineObject11 {
    pub fn new(session_id: String) -> InlineObject11 {
        InlineObject11 {
            session_id: session_id,
        }
    }
}


