/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineObject10 {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "request_token")]
    pub request_token: String,
}

impl InlineObject10 {
    pub fn new(username: String, password: String, request_token: String) -> InlineObject10 {
        InlineObject10 {
            username: username,
            password: password,
            request_token: request_token,
        }
    }
}


