/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineObject4 {
    #[serde(rename = "access_token")]
    pub access_token: String,
}

impl InlineObject4 {
    pub fn new(access_token: String) -> InlineObject4 {
        InlineObject4 {
            access_token: access_token,
        }
    }
}


