/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20012 {
    #[serde(rename = "id")]
    pub id: i32,
}

impl InlineResponse20012 {
    pub fn new(id: i32) -> InlineResponse20012 {
        InlineResponse20012 {
            id: id,
        }
    }
}


