/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20075Items {
    #[serde(rename = "original_value", skip_serializing_if = "Option::is_none")]
    pub original_value: Option<::models::InlineResponse20075OriginalValue>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl InlineResponse20075Items {
    pub fn new() -> InlineResponse20075Items {
        InlineResponse20075Items {
            original_value: None,
            action: None,
            id: None,
            time: None,
        }
    }
}


