/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20053Certifications {
    #[serde(rename = "BR", skip_serializing_if = "Option::is_none")]
    pub BR: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "DE", skip_serializing_if = "Option::is_none")]
    pub DE: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "RU", skip_serializing_if = "Option::is_none")]
    pub RU: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "AU", skip_serializing_if = "Option::is_none")]
    pub AU: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "TH", skip_serializing_if = "Option::is_none")]
    pub TH: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "KR", skip_serializing_if = "Option::is_none")]
    pub KR: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "GB", skip_serializing_if = "Option::is_none")]
    pub GB: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "FR", skip_serializing_if = "Option::is_none")]
    pub FR: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "US", skip_serializing_if = "Option::is_none")]
    pub US: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
    #[serde(rename = "CA", skip_serializing_if = "Option::is_none")]
    pub CA: Option<Vec<::models::InlineResponse20053CertificationsBr>>,
}

impl InlineResponse20053Certifications {
    pub fn new() -> InlineResponse20053Certifications {
        InlineResponse20053Certifications {
            BR: None,
            DE: None,
            RU: None,
            AU: None,
            TH: None,
            KR: None,
            GB: None,
            FR: None,
            US: None,
            CA: None,
        }
    }
}


