/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20065 {
    #[serde(rename = "stills", skip_serializing_if = "Option::is_none")]
    pub stills: Option<Vec<::models::InlineResponse20034Profiles>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
}

impl InlineResponse20065 {
    pub fn new() -> InlineResponse20065 {
        InlineResponse20065 {
            stills: None,
            id: None,
        }
    }
}


