/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20077 {
    #[serde(rename = "original_language", skip_serializing_if = "Option::is_none")]
    pub original_language: Option<String>,
    #[serde(rename = "number_of_episodes", skip_serializing_if = "Option::is_none")]
    pub number_of_episodes: Option<i32>,
    #[serde(rename = "networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<Vec<::models::InlineResponse20024Genres>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "backdrop_path", skip_serializing_if = "Option::is_none")]
    pub backdrop_path: Option<Value>,
    #[serde(rename = "genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Vec<::models::InlineResponse20024Genres>>,
    #[serde(rename = "popularity", skip_serializing_if = "Option::is_none")]
    pub popularity: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "number_of_seasons", skip_serializing_if = "Option::is_none")]
    pub number_of_seasons: Option<i32>,
    #[serde(rename = "vote_count", skip_serializing_if = "Option::is_none")]
    pub vote_count: Option<i32>,
    #[serde(rename = "first_air_date", skip_serializing_if = "Option::is_none")]
    pub first_air_date: Option<String>,
    #[serde(rename = "seasons", skip_serializing_if = "Option::is_none")]
    pub seasons: Option<Vec<::models::InlineResponse20077Seasons>>,
    #[serde(rename = "languages", skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<String>>,
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Vec<Value>>,
    #[serde(rename = "poster_path", skip_serializing_if = "Option::is_none")]
    pub poster_path: Option<Value>,
    #[serde(rename = "origin_country", skip_serializing_if = "Option::is_none")]
    pub origin_country: Option<Vec<String>>,
    #[serde(rename = "production_companies", skip_serializing_if = "Option::is_none")]
    pub production_companies: Option<Vec<Value>>,
    #[serde(rename = "original_name", skip_serializing_if = "Option::is_none")]
    pub original_name: Option<String>,
    #[serde(rename = "vote_average", skip_serializing_if = "Option::is_none")]
    pub vote_average: Option<f32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "episode_run_time", skip_serializing_if = "Option::is_none")]
    pub episode_run_time: Option<Vec<i32>>,
    #[serde(rename = "in_production", skip_serializing_if = "Option::is_none")]
    pub in_production: Option<bool>,
    #[serde(rename = "last_air_date", skip_serializing_if = "Option::is_none")]
    pub last_air_date: Option<String>,
    #[serde(rename = "homepage", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl InlineResponse20077 {
    pub fn new() -> InlineResponse20077 {
        InlineResponse20077 {
            original_language: None,
            number_of_episodes: None,
            networks: None,
            _type: None,
            backdrop_path: None,
            genres: None,
            popularity: None,
            id: None,
            number_of_seasons: None,
            vote_count: None,
            first_air_date: None,
            seasons: None,
            languages: None,
            created_by: None,
            poster_path: None,
            origin_country: None,
            production_companies: None,
            original_name: None,
            vote_average: None,
            name: None,
            episode_run_time: None,
            in_production: None,
            last_air_date: None,
            homepage: None,
            status: None,
        }
    }
}


