/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MediaFavoriteBody {
    #[serde(rename = "media_type")]
    pub media_type: crate::models::MediaType,
    #[serde(rename = "media_id")]
    pub media_id: i32,
    #[serde(rename = "favorite")]
    pub favorite: bool,
}

impl MediaFavoriteBody {
    pub fn new(
        media_type: crate::models::MediaType,
        media_id: i32,
        favorite: bool,
    ) -> MediaFavoriteBody {
        MediaFavoriteBody {
            media_type,
            media_id,
            favorite,
        }
    }
}
