/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MediaWatchlistBody {
    #[serde(rename = "media_type")]
    pub media_type: crate::models::MediaType,
    #[serde(rename = "media_id")]
    pub media_id: i32,
    #[serde(rename = "watchlist")]
    pub watchlist: bool,
}

impl MediaWatchlistBody {
    pub fn new(
        media_type: crate::models::MediaType,
        media_id: i32,
        watchlist: bool,
    ) -> MediaWatchlistBody {
        MediaWatchlistBody {
            media_type,
            media_id,
            watchlist,
        }
    }
}
