/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MovieTvExternalIds {
    #[serde(rename = "id")]
    pub id: i32,
}

impl MovieTvExternalIds {
    pub fn new(id: i32) -> MovieTvExternalIds {
        MovieTvExternalIds { id: id }
    }
}
