/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MoviedetailsSpokenLanguages {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "iso_639_1", skip_serializing_if = "Option::is_none")]
    pub iso_639_1: Option<String>,
}

impl MoviedetailsSpokenLanguages {
    pub fn new() -> MoviedetailsSpokenLanguages {
        MoviedetailsSpokenLanguages {
            name: None,
            iso_639_1: None,
        }
    }
}
