/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct PersonObject {
    #[serde(rename = "profile_path", skip_serializing_if = "Option::is_none")]
    pub profile_path: Option<String>,
    #[serde(rename = "adult", skip_serializing_if = "Option::is_none")]
    pub adult: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "known_for", skip_serializing_if = "Option::is_none")]
    pub known_for: Option<Vec<serde_json::Value>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "popularity", skip_serializing_if = "Option::is_none")]
    pub popularity: Option<f32>,
    #[serde(rename = "media_type")]
    pub media_type: Option<PersonMediaType>,
}

impl PersonObject {
    pub fn new() -> PersonObject {
        PersonObject {
            profile_path: None,
            adult: None,
            id: None,
            known_for: None,
            name: None,
            popularity: None,
            media_type: Some(PersonMediaType::Person),
        }
    }
}

///
#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum PersonMediaType {
    #[serde(rename = "person")]
    Person,
}
