/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TokenResponseWithExpiration {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "request_token", skip_serializing_if = "Option::is_none")]
    pub request_token: Option<String>,
}

impl TokenResponseWithExpiration {
    pub fn new() -> TokenResponseWithExpiration {
        TokenResponseWithExpiration {
            success: None,
            expires_at: None,
            request_token: None,
        }
    }
}
