/*
 * API
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct Video {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "iso_639_1", skip_serializing_if = "Option::is_none")]
    pub iso_639_1: Option<String>,
    #[serde(rename = "iso_3166_1", skip_serializing_if = "Option::is_none")]
    pub iso_3166_1: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "site", skip_serializing_if = "Option::is_none")]
    pub site: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
}

impl Video {
    pub fn new() -> Video {
        Video {
            id: None,
            iso_639_1: None,
            iso_3166_1: None,
            key: None,
            name: None,
            site: None,
            size: None,
            _type: None,
        }
    }
}

///
#[derive(Debug, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Trailer")]
    Trailer,
    #[serde(rename = "Teaser")]
    Teaser,
    #[serde(rename = "Clip")]
    Clip,
    #[serde(rename = "Featurette")]
    Featurette,
    #[serde(rename = "Opening Credits")]
    OpeningCredits,
}
